# Generated by Django 4.2.5 on 2023-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subjects_id',
            field=models.ManyToManyField(null=True, to='edu.subjects', verbose_name='Доступы к предметам'),
        ),
    ]
