# Generated by Django 4.2.5 on 2023-10-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
        ('users', '0002_alter_user_subjects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Класс', to='edu.classes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects_id',
            field=models.ManyToManyField(blank=True, to='edu.subjects', verbose_name='Доступы к предметам'),
        ),
    ]
