# Generated by Django 4.2.5 on 2023-10-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('is_done', models.BooleanField(verbose_name='Урок проведен')),
                ('topic', models.CharField(max_length=40, verbose_name='Тема урока')),
                ('home_work', models.CharField(max_length=40, verbose_name='Домашняя работа')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('lesson_id', models.ManyToManyField(to='edu.lessons', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Номер класса')),
                ('letter', models.CharField(max_length=1, verbose_name='Параллель')),
                ('sub_id', models.ManyToManyField(to='edu.subjects', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['id'],
            },
        ),
    ]
