# Generated by Django 4.2.8 on 2024-01-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата')),
                ('is_done', models.BooleanField(verbose_name='Урок проведен')),
                ('topic', models.TextField(verbose_name='Тема урока')),
                ('additionals', models.TextField(blank=True, null=True, verbose_name='Дополнительные материалы')),
                ('home_work', models.TextField(verbose_name='Домашняя работа')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-is_done', '-data'],
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('lesson_id', models.ManyToManyField(to='edu.lessons', verbose_name='Уроки')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=1, verbose_name='Номер класса')),
                ('letter', models.CharField(max_length=1, verbose_name='Параллель')),
                ('sub_id', models.ManyToManyField(to='edu.subjects', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['id'],
            },
        ),
    ]
