# Generated by Django 5.0.3 on 2024-03-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='document',
            field=models.FileField(blank=True, help_text='Это не обязательное поле', null=True, upload_to='documents/%Y/%m/', verbose_name='Файлы урока'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='number',
            field=models.CharField(max_length=2, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='additionals',
            field=models.TextField(blank=True, help_text='Это не обязательное поле', null=True, verbose_name='Дополнительные материалы'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='email',
            field=models.EmailField(blank=True, help_text='Это не обязательное поле', max_length=254, verbose_name='Почта учителя'),
        ),
    ]
