# Generated by Django 4.2.8 on 2024-01-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='data',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
