# Generated by Django 4.2.6 on 2023-10-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-is_done', '-data'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='additionals',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные материалы'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='home_work',
            field=models.TextField(verbose_name='Домашняя работа'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='topic',
            field=models.TextField(verbose_name='Тема урока'),
        ),
    ]
