# Generated by Django 4.2.5 on 2023-10-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='acces_class',
            field=models.ManyToManyField(to='edu.classes', verbose_name='Доступность к классам'),
        ),
    ]
