# Generated by Django 4.2.5 on 2023-10-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_subjects_acces_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='acces_class',
            new_name='access_class',
        ),
    ]
