# Generated by Django 4.2.8 on 2024-03-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_alter_lessons_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['-data'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='is_done',
        ),
    ]
