# Generated by Django 4.2.5 on 2023-10-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_rename_acces_class_subjects_access_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='access_class',
        ),
    ]
