# Generated by Django 5.0.3 on 2024-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_alter_lessons_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='document',
            field=models.FileField(help_text='Это не обязательное поле', null=True, upload_to='user_directory_path', verbose_name='Файлы урока'),
        ),
    ]
