# Generated by Django 5.0.3 on 2024-04-19 15:53

import edu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_alter_lessons_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='document',
            field=models.FileField(blank=True, help_text='Это не обязательное поле', null=True, upload_to=edu.models.user_directory_path, verbose_name='Файлы урока'),
        ),
    ]
